site_name: Serverless Sample
repo_name: fujiwaki/serverless_sample_for_article
repo_url: https://github.com/fujiwaki/serverless_sample_for_article
copyright: Copyright &copy; 2024 fujiwaki

nav:
  - Home: index.md
  - API: api.md
  - Reference: reference/
  - Test Coverage: coverage.md

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: indigo
  font:
    text: Fira Sans
    code: Fira Code
  features:
    - navigation.tabs
    - navigation.top
    - toc.follow
    - toc.integrate

extra_css:
  - stylesheets/code_select.css
  - stylesheets/mkdocstrings.css

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/gen_api_page.py
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            merge_init_into_class: true
            show_signature_annotations: true
  - coverage:
      html_report_dir: docs/htmlcov
  - swagger-ui-tag

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
